
CREATE TABLE Users(
    UserID SERIAL PRIMARY KEY,
    Username TEXT NOT NULL,
    Email TEXT UNIQUE NOT NULL,
    UserPassword TEXT NOT NULL,
    RegistrationDate DATE NOT NULL,
    CashBalance NUMERIC (10, 2) DEFAULT 0 
); 

CREATE TABLE Roles(
    RoleID SERIAL PRIMARY KEY,
    RoleName VARCHAR(15) UNIQUE NOT NULL,
    FullDescription TEXT 
);

CREATE TABLE UserProfiles(
    UserID INTEGER PRIMARY KEY REFERENCES Users(UserID) ON DELETE CASCADE,
    RoleID INTEGER REFERENCES Roles(RoleID) ON DELETE RESTRICT,
    FullName VARCHAR(127) NOT NULL,
    Bio TEXT,
    Avatar VARCHAR(255),
    UserLocation  VARCHAR (63),
    DateOfBirth DATE NOT NULL
);

CREATE TABLE UserActivityLog(
    LogID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    Activity TEXT NOT NULL,
    LoggedAt TIMESTAMP NOT NULL
);

CREATE TABLE Games(
    GameID SERIAL PRIMARY KEY,
    Title VARCHAR(63) NOT NULL,
    GameDescription TEXT,
    ReleaseDate DATE NOT NULL,
    Developer VARCHAR(63) NOT NULL,
    Price NUMERIC(10, 2) DEFAULT 0,
    ViewRestriction BOOLEAN DEFAULT TRUE
);

CREATE TABLE UserGames(
    UserGameID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    GameID INTEGER NOT NULL REFERENCES Games(GameID) ON DELETE CASCADE,
    PurchaseDate DATE NOT NULL,
    PlayTime INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE Achievements(
    AchievementID SERIAL PRIMARY KEY,
    GameID INTEGER NOT NULL REFERENCES Games(GameID),
    Title VARCHAR(63) NOT NULL,
    Overview TEXT,
    Points INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE UserAchievements(
    UserAchievememntID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    AchievementID INTEGER NOT NULL REFERENCES Achievements(AchievementID) ON DELETE CASCADE,
    UnlockDate DATE NOT NULL
);

CREATE TABLE Friends(
    FriendshipID SERIAL PRIMARY KEY,
    UserID1 INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    UserID2 INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE 
);

CREATE TABLE ChatMessages(
    MessageID SERIAL PRIMARY KEY,
    SenderID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    ReceiverID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    Content TEXT NOT NULL,
    SendDate TIMESTAMP NOT NULL
);

CREATE TABLE GameProgress(
    ProgressID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    GameID INTEGER NOT NULL REFERENCES Games(GameID) ON DELETE CASCADE,
    SaveData TEXT NOT NULL,
    LastUpdated TIMESTAMP NOT NULL
);

CREATE TABLE Transactions(
    TransactionID SERIAL PRIMARY KEY,
    TransactionCode VARCHAR(36) UNIQUE NOT NULL,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    GameID INTEGER NOT NULL REFERENCES Games(GameID) ON DELETE CASCADE,
    Amount INTEGER NOT NULL DEFAULT 0,
    TrType INTEGER NOT NULL REFERENCES TransactionType(TypeID) ON DELETE RESTRICT,
    TransactionTime TIMESTAMP NOT NULL
);

CREATE TABLE Reviews(
    ReviewID SERIAL PRIMARY KEY,
    UserID INTEGER NOT NULL REFERENCES Users(UserID) ON DELETE CASCADE,
    GameID INTEGER NOT NULL REFERENCES Games(GameID) ON DELETE CASCADE,
    Rating INTEGER NOT NULL DEFAULT 0,
    Content TEXT,
    PostDate TIMESTAMP NOT NULL,
    CHECK (Rating >= 0 AND Rating <= 10)
);

CREATE TABLE Tags(
    TagID SERIAL PRIMARY KEY,
    TagName VARCHAR(31) NOT NULL UNIQUE,
    TagDescription TEXT NOT NULL
);

CREATE TABLE GameTags(
    TagID INTEGER NOT NULL REFERENCES Tags(TagID) ON DELETE CASCADE,
    GameID INTEGER NOT NULL REFERENCES Games(GameID) ON DELETE CASCADE
);

CREATE TABLE TransactionType(
    TypeID SERIAL NOT NULL PRIMARY KEY,
    TypeName varchar (32) NOT NULL
);